### PR TITLE
Add option to remove CD-ROM drives

### LINKED ISSUE #214: CD-ROM devices no longer removed
It looks like in v2.1 new functionality was added to eject the CD-ROM drives at the end of the Packer build rather than deleting them (#173).  This is causing a break in our pipeline as subsequent Packer builds expected to be able to partition drives at the E: and F: spots that are now occupied by the CD-ROM drives that were previously deleted.  Is there a possibility of adding a parameter that can toggle between these two scenarios?

Thanks.  Overall great plugin.

### PR DESCRIPTION
**Pull request by eriweb**
PR #173 changed the default behavior of removing CD-ROM drives and ejects them instead.
This PR adds an option called `remove_cdrom` (default false) that
when enabled removed any CD-ROM devices from the VM/template.

This should fix #214

### CODE REVIEW

**Comment by danonh** [comment]
Hi terbolous,
This option does not work for me, I get 
Errors validating build 'rails'. 1 error(s) occurred:
* unknown configuration key: "remove_cdrom"

I use latest builder provided by jetbrains
If this works for you can you tell if "remove_cdrom" removes specific drive or all cdrom drives configured within VM? I need an option that removes only specific cd-rom where vmtools has been mounted.
Thanks,

**Comment by terbolous** [comment]
Not sure if jetbrains has a service that allows you to download pull
requests or not. If not you’ll have to compile yourself.

Currently it removes all cdroms, i am not sure how to specify a single one
in a convenient way

fre. 3. mai 2019 kl. 12:33 skrev danonh <notifications@github.com>:

**Comment by MFiederlein** [comment]
Working well for me, thanks. Please, can this be merged?

**Comment by theonlydude1** [comment]
Hello, please can you merge this one ? We are forced to use manual steps to remove the CD....
Thanks !

**Comment by Bandyman** [comment]
Yes, please get this merged. It would be super handy for us!

**Comment by rhockenbury** [comment]
@VladRassokhin  Can this be merged, or is it waiting for something?

**Comment by atiniir** [comment]
> @VladRassokhin Can this be merged, or is it waiting for something?

@rhockenbury i think this change will need to be re-submitted against the packer main repo since the plugin itself has been migrated over there. 

maybe?

**Comment by daxgames** [comment]
@terbolous Did you ever look at submitting this change to the main packer since this plugin is now a part of the packer project?  It is unreleased at this point but this change would be nice to have.

**Comment by daxgames** [comment]
@terbolous I have pulled down the packer source and have a branch with your change added.  I am testing it now.

**Comment by terbolous** [comment]
@daxgames No sorry, I didn't notice the plugin going upstream. I have no issues with you handling the PR there

**Comment by daxgames** [comment]
This has been merged into the Packer main repo and can be closed if its not going to be merged here. [vsphere iso remove cdroms #8690](https://github.com/hashicorp/packer/pull/8690)

**Pull request closed without merging**
