### PR TITLE
add centos 7 examples

### PR DESCRIPTION
**Pull request by remijouannet**
an example for building centos7 template

### CODE REVIEW

**Comment by dkirrane** [comment]
@remijouannet I tried your CentOS example on the lastest release `v2.0.1` on vsphere `6.5.0, 10175896` but hit the prompt when installing `open-vm-tools`
image

To solve I had to move from `%packages` to `%post` section of the kickstart
```
yum install -y epel-release
yum install -y open-vm-tools
```

**Comment by dkirrane** [comment]
@remijouannet I tried your CentOS example on the lastest release `v2.0.1` on vsphere `6.5.0, 10175896` but hit the prompt when installing `open-vm-tools`
image

To solve I had to move from `%packages` to `%post` section of the kickstart
```
yum install -y epel-release
yum install -y open-vm-tools
```

**Comment by dkirrane** [comment]
@remijouannet I tried your CentOS example on the lastest release `v2.0.1` on vsphere `6.5.0, 10175896` but hit the prompt when installing `open-vm-tools`
image

To solve I had to move from `%packages` to `%post` section of the kickstart
```
yum install -y epel-release
yum install -y open-vm-tools
```

**Comment by deryni** [comment]
I don't believe the `$variables` in the `repo` config lines are expanded here (so they aren't doing anything and those lines aren't working the way they were intended to).

That said, `open-vm-tools` should be on the installation ISO (even the ancient 7.0 1406 ISO mentioned in the comment).

`epel-release` may or may not be on the ISO (it is in the `extras` repo and I forget if that is included on the ISO or not.

I'm not sure how the error in that screenshot came about here exactly.

**Comment by remijouannet** [comment]
Hello @deryni
I've built centos 6/7 with this plugins
- $variables are expanded otherwise kickstart throw an error because it can't read repometadata.xml
- open-vm-tools is in epel repo (if don't add the repo before installing it, it failed
- epel-release package is found on base centos repo

**Comment by remijouannet** [comment]
the current checksum of the ISO I used is 714acc0aefb32b7d51b515e25546835e55a90da9fb00417fbee2d03a62801efd

**Comment by remijouannet** [comment]
hello @mkuzmin following #164 and #185 i updated this PR to use the two features

**Comment by deryni** [comment]
@remijouannet The RedHat documentation explicitly says that variables don't work with `--baseurl` ... so I don't know what to tell you. If they work ... I guess that's good? (Maybe the documentation doesn't mean _all_ the variables?)

[repo (optional)](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/installation_guide/sect-kickstart-syntax#idm140037251904848):

> --baseurl= - The URL to the repository. The variables that can be used in yum repo config files are not supported here. This option cannot be used together with the --mirrorlist option in the same repository definition.

Also, I finally looked into what `augeas` is because of this PR so thanks for that. It looks _super_ handy.

**Comment by VladRassokhin** [comment]
This repo is deprecated. Please open PR in [official Packer repository](https://github.com/hashicorp/packer) if it's still relevant.

**Pull request closed without merging**
