### PR TITLE
Update folder.go

### PR DESCRIPTION
**Pull request by raisullip**
the path /%v/vm/%v breaks, it should be /%v/%v ...thanks.

### CODE REVIEW

**Comment by mkuzmin** [comment]
I'm pretty sure the current code works correctly.
Could you provide an example please

**Comment by raisullip** [comment]
Any updates ? thanks

**Comment by mkuzmin** [comment]
This `/vm/` piece is an internal path format used by vSphere API and ovftool.
Your issue is caused by typos in datacenter or folder name, or insufficient permissions.

Please let me know if you still need help.

**Comment by raisullip** [comment]
Hi Michael, you are correct, /vm/ is the default path for vCenter and vSphere, our issue is because our paths start with a virtual directory.

The plugin does not work if the datacenter object is nested inside of a folder. For example:

"datacenter": "Folder1/MyDatacenter",

Will output:
==> vsphere-iso: Creating VM...
Build 'vsphere-iso' errored: error creating vm: folder '/MyDatacenter/vm' not found

The issue is that although the plugin can successfully locate "Folder1/MyDatacenter", it will still attempt to create the VM into "/MyDatacenter/vm" instead of "Folder1/MyDatacenter/vm"

Specifying a folder does not help since it will only append the folder to the end. For example:

"datacenter": "Folder1/MyDatacenter",
"Folder": "Folder2"

Will output:
==> vsphere-iso: Creating VM...
Build 'vsphere-iso' errored: error creating vm: folder '/MyDatacenter/vm/Folder2' not found

**Comment by mkuzmin** [comment]
aha, this makes a sense now.
Could you post this as a separate issue, please? I'll take a look.

**Pull request closed without merging**
