### PR TITLE
jetbrains-infra/packer-builder-vsphere#229

### PR DESCRIPTION
**Pull request by ablackrw**
* `README.md`: Document new `disable_stop_instance` parameter.
* `step_shutdown.go`: Run gofmt.
  (ShutdownConfig): Add DisableStopInstance variable with annotation.
  (Run): No-op VM shutdown process with message if DisableStopInstance is set.

### CODE REVIEW

**Comment by VladRassokhin** [comment]
Using negation in parameter name (`disable_xxx`) may be confuging, I'd recommend to change it to `stop_after_last_provisioner` (or similar) with default value `true`

**Comment by ablackrw** [comment]
The name `disable_stop_instance` was chosen for consistency with the alicloud ecs and amazon family of builders provided by hashicorp. I did some quick poking around in the packer code base, and I didn't find any other builders that supported this sort of bypass mechanism.

While it might be nice to frame the option with a default value of true, I could see difficulties in distinguishing between an unspecified value for the switch and a user-specified value of false. A quick scan of the docker documentation fails to turn up circumstances where a boolean will default to true.

**Comment by VladRassokhin** [comment]
Ah, then it's ok to use that name for consistency.

**Review by VladRassokhin — APPROVED** [review]

**Comment by VladRassokhin** [comment]
This repo is deprecated. Please open PR in [official Packer repository](https://github.com/hashicorp/packer) if it's still relevant. Sorry for not reaching out earlier :(

**Pull request closed without merging**
