### PR TITLE
remove Cache service and make builder compatible with 1.4.0

### PR DESCRIPTION
**Pull request by azzeddinefaik**
ref : https://github.com/hashicorp/packer/issues/7622
 
do a pull request to the vsphere builder to update it to the new breaking changes; the changes are documented in this PR: https://github.com/hashicorp/packer/pull/7583/files, ( this would give #7168 a really nice head start )

### CODE REVIEW

**Comment by VladRassokhin** [comment]
Thanks, though I've merged another pull request (#246)

**Comment by kamalika-majumder** [comment]
I am still facing this issue. I am using packer 1.4.3

---------------------
2019/09/11 13:09:33 Preparing build: vsphere-iso
2019/09/11 13:09:33 Waiting on builds to complete...
2019/09/11 13:09:33 Starting build run: vsphere-iso
2019/09/11 13:09:33 Running builder: vsphere-iso
2019/09/11 13:09:33 [INFO] (telemetry) Starting builder vsphere-iso
2019/09/11 13:09:33 ui: [1;32m==> vsphere-iso: Retrieving ISO[0m
2019/09/11 13:09:33 packer-builder-vsphere-iso.macos: 2019/09/11 13:09:33 Acquiring lock to download: http://stable.release.core-os.net/amd64-usr/current/coreos_production_iso_image.iso
2019/09/11 13:09:33 packer-builder-vsphere-iso.macos: 2019/09/11 13:09:33 [ERR] Cache.Lock error: rpc: can't find service Cache.Lock
2019/09/11 13:09:33 packer-builder-vsphere-iso.macos: 2019/09/11 13:09:33 Parsed URL: &url.URL{Scheme:"http", Opaque:"", User:(*url.Userinfo)(nil), Host:"stable.release.core-os.net", Path:"/amd64-usr/current/coreos_production_iso_image.iso", RawPath:"", ForceQuery:false, RawQuery:"", Fragment:""}
2019/09/11 13:09:33 ui: [0;32m    vsphere-iso: Error downloading: open : no such file or directory[0m
2019/09/11 13:09:33 ui error: [1;31m==> vsphere-iso: ISO download failed.[0m
2019/09/11 13:09:33 packer-builder-vsphere-iso.macos: 2019/09/11 13:09:33 [ERR] Cache.Unlock error: rpc: can't find service Cache.Unlock
2019/09/11 13:09:33 [INFO] (telemetry) ending vsphere-iso
2019/09/11 13:09:33 ui error: [1;31mBuild 'vsphere-iso' errored: ISO download failed.[0m
2019/09/11 13:09:33 machine readable: error-count []string{"1"}
2019/09/11 13:09:33 ui error: 
==> Some builds didn't complete successfully and had errors:
2019/09/11 13:09:33 machine readable: vsphere-iso,error []string{"ISO download failed."}
2019/09/11 13:09:33 ui error: --> vsphere-iso: ISO download failed.
2019/09/11 13:09:33 ui: 
==> Builds finished but no artifacts were created.
2019/09/11 13:09:33 [INFO] (telemetry) Finalizing.
2019/09/11 13:09:34 waiting for all plugin processes to complete...
2019/09/11 13:09:34 /Users/kamalikamajumder/CloudKata/Dkatalis/VMware/packer/CoreOs/packer-builder-vsphere-iso.macos: plugin process exited

**Comment by VladRassokhin** [comment]
@kamalika-majumder because it's not released yet

**Comment by kamalika-majumder** [comment]
Is there a release date decided yet for this.

**Comment by VladRassokhin** [comment]
@kamalika-majumder No, but I'd try to find some time and go through all issues and PRs

**Pull request closed without merging**
