### PR TITLE
Boot command

### PR DESCRIPTION
**Pull request by mkuzmin**
`boot_command` parameter for keyboard typing.

[Special keys](https://www.packer.io/docs/builders/vmware-iso.html#boot-command) like `<bs>`, `<leftAltOn>`, and `<wait>` are supported.
`PACKER_KEY_INTERVAL` environment variable is supported.

vSphere 6.5 is required as new API is used to send USB codes instead of VNC connection.

`http_directory` parameter is not implemented but preseed files can be placed onto a floppy drive, see an example for Ubuntu.

### CODE REVIEW

**Comment by patrickmslatteryvt** [comment]
Any chance of getting the `http_directory` parameter for support of Fedora?
As of [Fedora 18](https://docs-old.fedoraproject.org/en-US/Fedora//html/Installation_Guide/sect-boot-options-removed.html
) support for kickstart files on a floppy was removed.
```
ks=floppy
Specified a floppy disk as the Kickstart file source. Floppy drives are not supported anymore.
```

Alternatively Fedora supports USB media for the kickstarts.
https://docs.fedoraproject.org/f27/install-guide/advanced/Kickstart_Installations.html

**Comment by seanmalloy** [comment]
@patrickmslatteryvt have you considered adding a kickstart file into a custom install ISO?

I have successfully done this with RHEL, but have never tried doing this with Fedora. I've also not been able to successfully use this plugin in my environment due to lack to ESXi cluster support. But once cluster support is added my plan is to test the custom install ISO approach. I'm restricted to vCenter v6.0 in my environment, so using the `boot_command` option will not work for me.

Here are some docs for how to embed a kickstart file into a custom RHEL install ISO. You may be able to adapt these instructions to work with Fedora. I'd be fascinated to know if you are able to get this to work with Fedora with the `vsphere-iso` plugin.

https://access.redhat.com/solutions/60959
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html-single/anaconda_customization_guide/
http://www.smorgasbork.com/2014/07/16/building-a-custom-centos-7-kickstart-disc-part-1/

**Comment by patrickmslatteryvt** [comment]
@seanmalloy I didn't find it necessary to do that since Fedora 27 simply treated the floppy image as if it were a hard disk as I showed in code above. (everything's just a file!)
I was trying this against a single node vSphere v6.5.x deployment that I use for development so the cluster limitation did not impact me. You might consider trying a nested instance of vSphere v6.5.x running in your v6.0.x cluster, that would allow you to test the new plugin at least (assuming that security restrictions are not preventing you from doing that)
See:
[Nested ESXi Enhancements in vSphere 6.5](https://www.virtuallyghetto.com/2016/10/nested-esxi-enhancements-in-vsphere-6-5.html)
[Updated Nested ESXi 6.0u3 & 6.5d Virtual Appliances
](https://www.virtuallyghetto.com/2017/05/updated-nested-esxi-6-0u3-6-5d-virtual-appliances.html)

**Comment by mkuzmin** [comment]
you don't have to modify ISO images, the plugin now allows to mount multiple CD-ROM devices in parallel.

Right now I'm automating macOS installation. It also doesn't have floppy drives, so the scripts are placed onto a custom ISO image.
Probably, in future we will need to add a functionality to generate and upload such ISO files the same way as we do it for floppies.

**Pull request merged**
