### PR TITLE
WIP: Add datastorecluster support

### LINKED ISSUE #73: Support datastoreclusters
I would like to propose support of datastoreclusters. In our use case datastores are grouped in datastoreclusters akin to how clusters are used to group hosts. In our other vSphere related automation (i.e bootstrapping VMs based on templates) we already make use of a datastorecluster parameter, where we let vSphere decide on which datastore to place it.

This feature would make the `datastore` and `datastorecluster` parameter mutually exclusive since in case of the latter vSphere's DRS takes care of suggesting a fitting `datastore` inside the specified `datastorecluster` based on the size of all disks present inside the template. 

Output of `govc find . -type s`:

```
/DC/datastore/DC1EXP01/xpaa_vi_215
/DC/datastore/DC1EXP01/xpaa_vi_217
/DC/datastore/DC1EXP01/xpaa_vi_219
/DC/datastore/DC1EXP01/xpaa_vi_221
```

Let me know if there is interest in this type of functionality and whether you consider a PR for this since I have this part working for the `iso` builder already based on govc's `create` inside the `vm` package.
See usage of the `recommendDatastore` function in [create.go#L333](https://github.com/vmware/govmomi/blob/master/govc/vm/create.go#L333) and declare in [create.go#L455](https://github.com/vmware/govmomi/blob/master/govc/vm/create.go#L455). I found this usage fitting quite nicely with this existing codebase, so all credit goes to them :).

### PR DESCRIPTION
**Pull request by ghost**
WIP, once done fixes #73. At this current stage only supports the `iso`-builder. 

Utilizes the [StorageResourceManager's](https://www.vmware.com/support/developer/converter-sdk/conv50_apireference/vim.StorageResourceManager.html) [RecommendDatastores](https://www.vmware.com/support/developer/converter-sdk/conv50_apireference/vim.StorageResourceManager.html#recommendDatastores) method to get a Storage DRS recommendation of a fitting `datastore` inside specified `datastorecluster`. Doesn't actually use the [ApplyStorageDrsRecommendationToPod_Task](https://www.vmware.com/support/developer/converter-sdk/conv50_apireference/vim.StorageResourceManager.html#applyRecommendationToPod) to apply the recommendations but iterates through eligible disks and pins the recommended datastore for each disk, so means that this should be ready to support multiple disks once #68 comes through. 
I'll work on the `clone`-builder once given the go i.e this is aligned to the project.

Tested with: "Clusters without DRS", "Clusters with DRS", cannot reproduce "Resource Pools/custom resource pools" since only the default ones exist in our environment. Happy for any feedback.

### CODE REVIEW

**Comment by mkuzmin** [comment]
Hi Josip. Sorry for late response, I was busy preparing a stable release. 
Could you rebase the branch, so I can review the code. Thanks!

**Comment by xjsp** [comment]
No worries will do, atm fails since [f46f373](https://github.com/jetbrains-infra/packer-builder-vsphere/commit/f46f373e3a19a7bd3a5d459c48d2284ac3b4d0a1), will push and rebase once I've resolved the issues on my side.

**Comment by synth3tk** [comment]
Just checking in on the status of this.

**Comment by bhundven** [comment]
Hasn't been updated in a while, is this still in progress/active?

**Comment by mkuzmin** [comment]
I'll try to finish this in a branch.

**Comment by codyja** [comment]
Any chance this could get knocked out soon? I would be extremely grateful! Thank you

**Comment by bandit145** [comment]
What is the status on this? This would be really helpful to have (at least for me and my org)!

**Comment by bhundven** [comment]
This project has merged to upstream packer. in 1.5.2 (now at 1.5.5).
Looks like someone should open a new pull request with upstream packer, or open an issue to see if someone else can.

**Pull request merged**
