### PR TITLE
Update plugin to Packer ^1.4 compatibility

### PR DESCRIPTION
**Pull request by clingle**
Closes #240, fixes https://github.com/hashicorp/packer/issues/7622

Any feedback is welcome.

### Summary of changes:
- Changed "http_port" from uint to int for step_boot_command (Fix for https://github.com/hashicorp/packer/pull/7423)
- Implemented API changes for context cancellation of builders (Fix for https://github.com/hashicorp/packer/pull/7440)
- Update packer (1.4.1) and govmomi (0.20.0) go modules
- Run `go mod tidy` to clean up unnecessary go.mod and go.sum entries

<hr>

### Notes:
- I've already signed the Hashicorp CLA for Packer, so this is non-blocking for https://github.com/hashicorp/packer/pull/7168

### CODE REVIEW

**Comment by gowthamakanthan** [comment]
Any update on my issue? 

`[gowgopal@terra-code-srv1 cdev]$ packer version
Packer v1.4.1
[gowgopal@terra-code-srv1 cdev]$ packer build -var 'vsphere_vm_name=std-cent7-template' -debug centos7.json
Failed to initialize build 'vsphere-iso': builder type not found: vsphere-iso
Debug mode enabled. Builds will not be parallelized.
vsphere-iso output will be in this color.


==> Builds finished but no artifacts were created.
[gowgopal@terra-code-srv1 cdev]$`

**Comment by clingle** [comment]
@gowthamakanthan This plugin doesn't work with Packer 1.4.1 right now, but you'll need to make sure that the plugin is in the same path as the Packer binary file, and that the plugin has the execute bit set on its file permissions.

Example:  If the packer binary is in `/bin/packer` you'd need the plugin to be located at `/bin/packer-builder-vsphere-iso.linux` with permissions of at least `700`, but probably `755` would be preferred.

If you want to use this plugin with Packer version 1.4.1 go to my fork of this repo and download the [v2.4 release](https://github.com/clingle/packer-builder-vsphere/releases/tag/v2.4) I tagged there. Otherwise you need to get [Packer version 1.3.5](https://github.com/hashicorp/packer/releases/tag/v1.3.5) for it to work.

**Comment by gowthamakanthan** [comment]
Hello @clingle , 

Thanks for the reply. I have checked the permissions and compared with the working server and am not finding any difference. I have tried to install other versions as well. But no luck. 
Only on this server, it's behaving weird. 


`[root@terra-code-srv1 cdev]# packer build -var 'vsphere_vm_name=std-cent7-template2' -debug centos7.json
Failed to initialize build 'vsphere-iso': builder type not found: vsphere-iso
Debug mode enabled. Builds will not be parallelized.
vsphere-iso output will be in this color.


==> Builds finished but no artifacts were created.
[root@terra-code-srv1 cdev]# ls -l /usr/local/sbin/packer
-rwxr-xr-x 1 root root 147034641 Jun  6 12:30 /usr/local/sbin/packer
[root@terra-code-srv1 cdev]# ls -l /usr/sbin/packer
lrwxrwxrwx 1 root root 15 Jun  7 03:32 /usr/sbin/packer -> cracklib-packer
[root@terra-code-srv1 cdev]# ls -l /usr/sbin/cracklib-packer
-rwxr-xr-x. 1 root root 11328 Jun 10  2014 /usr/sbin/cracklib-packer
[root@terra-code-srv1 cdev]# ls -l /usr/local/go/src/github.com/hashicorp/packer/packer | wc -l
45
[root@terra-code-srv1 cdev]# ls -l /usr/local/go/src/github.com/hashicorp/packer | wc -l
36
[root@terra-code-srv1 cdev]#
`

**Comment by VladRassokhin** [comment]
Thanks. I've manually rebased and merged into master

**Pull request closed without merging**
