### PR TITLE
add remove if exists

### PR DESCRIPTION
**Pull request by remijouannet**
adding a option to remove another VM/template if it has the same name, 
this option only doing the Destroy it doesn't stop the VM if it's running

### CODE REVIEW

**Comment by VladRassokhin** [comment]
Maybe change name parameter to `replace_existing` or just `replace`? 
@mkuzmin What do you think?

**Comment by mkuzmin** [comment]
it was discussed in #50.
The feature is great, but adding a parameter makes it too permanent. I like suggested approach with `-force` command line flag.

**Comment by remijouannet** [comment]
ho I didn't know about that flag, I will look into that

**Comment by remijouannet** [comment]
@mkuzmin better ?

**Comment by remijouannet** [comment]
@mkuzmin done

**Comment by obokaman-com** [comment]
@remijouannet 👏 thanks

**Comment by jcoconnor** [comment]
💯

**Comment by dkirrane** [comment]
@remijouannet I've tried this in latest version but it fails if the VM is powered on

```
==> vsphere-clone: the vm/template myvm-1.2.1-tmpl already exists, but deleting it due to -force flag
==> vsphere-clone: Cloning VM...
==> vsphere-clone: The name 'myvm-1.2.1-tmpl' already exists.
==> vsphere-clone: Step "StepCloneVM" failed
```

**Comment by remijouannet** [comment]
This option is more mean to be use with a template rather than a running VM

**Pull request merged**
