### PR TITLE
Add ability to control nested hardware virtualization

### PR DESCRIPTION
**Pull request by dtretyakov**
This change allows to configure nested virtualization for VMs

Issue: #45

### CODE REVIEW

**Comment by mkuzmin** [comment]
New `"NestedHV": true` option

**Comment by mkuzmin** [comment]
@dtretyakov thank you!

**Comment by casey-robertson** [comment]
Here's my JSON file here:  https://gist.github.com/casey-robertson/cb6a2826b4a97ea2d14a1f9869f3d260

the NestedHV flag doesn't seem to set the flag on the VM.  Any thoughts?

**Comment by mkuzmin** [comment]
please open a new issue. At the moment it's implemented in `vsphere-clone` builder only

**Pull request merged**
