### PR TITLE
Feature stepremoteupload

### PR DESCRIPTION
**Pull request by remijouannet**
Sorry this PR also include everything in https://github.com/jetbrains-infra/packer-builder-vsphere/pull/144

this PR include a step to upload an iso to vpshere for the builder vsphere-iso

### CODE REVIEW

**Comment by steven-sheehy** [comment]
I was looking for this feature as well to have feature parity with vmware-iso. Any update when this could be reviewed? Thanks @remijouannet for your contribution.

**Comment by remijouannet** [comment]
hey @steven-sheehy meanwhile you can use my build https://github.com/remijouannet/packer-builder-vsphere/releases/tag/v2.1-alpha

**Comment by steven-sheehy** [comment]
@remijouannet Thanks, I tried it and it does not allow you to use the old approach of only specifying iso_paths:

```
1 error(s) occurred:
* One of iso_url or iso_urls must be specified.
```

**Comment by remijouannet** [comment]
here isa working example, don't use iso_path

"iso_urls": [
        "https://mirrors.ircam.fr/pub/CentOS/7/isos/x86_64/CentOS-7-x86_64-Minimal-1804.iso"
      ],
      "iso_checksum_type" : "sha256",
      "iso_checksum" : "714acc0aefb32b7d51b515e25546835e55a90da9fb00417fbee2d03a62801efd",
      "iso_target_path" : "/tmp/CentOS-7-x86_64-Minimal-1804.iso",

**Comment by steven-sheehy** [comment]
Yes, I also have the iso_urls approach working. My point was I think the maintainers will probably want to keep the old approach as well. iso_paths is also still mentioned in README and in examples as supported.

**Comment by remijouannet** [comment]
Yeah but iso_paths is use for mouting a ISO that is already upload on the esxi, my patch doesn't remove that you juste have too choose between the two methods

Anyway i will wait for the review to see if this behavior is ok or not

**Comment by segator** [comment]
it works nicely!!!

are you going to integrate it? I'm planning to use this plugin for my development automatic proceses with jenkins.

**Comment by mkuzmin** [comment]
I'd happy to merge this! please rebase the branch onto `master`

**Comment by remijouannet** [comment]
Will work on that :relaxed:

**Comment by remijouannet** [comment]
new PR https://github.com/jetbrains-infra/packer-builder-vsphere/pull/164

**Comment by swerveshot** [comment]
Great work on this issue guys. Now with this feature added combining Packer with Terraform almost brings a Vagrant-like experience to vSphere. I'm amazed that it takes a community project to achieve this and Hashicorp still requires you use a nasty SSH backdoor.

**Pull request closed without merging**
